<?php

namespace Lv\LibraryBundle\Repository;

/**
 * BookGenresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookGenresRepository extends \Doctrine\ORM\EntityRepository
{
}
