<?php

namespace Lv\LibraryBundle\Repository;

/**
 * CustomerBooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerBooksRepository extends \Doctrine\ORM\EntityRepository
{
}
