<?php

namespace Lv\LibraryBundle\Repository;

/**
 * LibraryBooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibraryBooksRepository extends \Doctrine\ORM\EntityRepository
{
}
